services:
  nginx:
    container_name: nginx
    build:
      context: ./proxy/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - './backend:/app/'
      - './proxy/nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend
    networks:
      - funny

  backend:
    build:
      context: ./backend/php/
      args:
        WWWUSER: 'laravel'
        WWWUID: '1000'
    container_name: php
    volumes:
      - './backend:/app/'
    depends_on:
      - db
    networks:
      - funny
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

      - MAIL_MAILER=${MAIL_MAILER}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_ENCRYPTION=${MAIL_ENCRYPTION}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - MAIL_FROM_NAME=${APP_NAME}

  frontend:
    container_name: frontend
    build:
      context: ./frontend/client
      dockerfile: Dockerfile
      args:
        - AXIOS_BASEURL=http://127.0.0.1/api
        - AXIOS_BROWSER_BASEURL=/api
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: "npm run dev"
    environment:
      - AXIOS_BASEURL=http://127.0.0.1/api
      - AXIOS_BROWSER_BASEURL=/api
    volumes:
      - ./frontend/client:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - funny

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - funny
    environment:
      ADMINER_DEFAULT_SERVER: 'pgsql'
      ADMINER_DEFAULT_TYPE: 'postgresql'
    depends_on:
      - db