services:
  nginx:
    container_name: nginx
    build:
      context: ./proxy/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - './backend:/app/'
      - './proxy/nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend
    networks:
      - funny

  backend:
    build:
      context: ./backend/php/
      args:
        WWWUSER: 'laravel'
        WWWUID: '1000'
    container_name: php
    volumes:
      - './backend:/app/'
    depends_on:
      - db
    networks:
      - funny
    env_file:
      - .env

  frontend:
    container_name: frontend
    build:
      context: ./frontend/client
      dockerfile: Dockerfile
      args:
        - AXIOS_BASEURL=http://127.0.0.1/api
        - AXIOS_FRONTEND=http://127.0.0.1
        - AXIOS_BROWSER_BASEURL=/api
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: "npm run dev"
    environment:
      - AXIOS_BASEURL=http://127.0.0.1/api
      - AXIOS_BROWSER_BASEURL=/api
    volumes:
      - ./frontend/client:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - funny