version: "3.9"
services:
  nginx:
    image: nginx:1.20
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - './backend:/app/'
      - './proxy/nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
    networks:
      - funny
  db:
    image: postgres:16
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST==${DB_HOST}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - funny


networks:
  funny:
    driver: bridge