version: "3.9"
services:
  backend:
    container_name: app
    build:
      context: app
      dockerfile: Dockerfile
    restart: always
    expose:
      - "9000"
    ports:
      - "9000:9000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: ./frontend/client
      dockerfile: Dockerfile
      args:
        - AXIOS_BASEURL=https://funny-how.com/api
        - AXIOS_BROWSER_BASEURL=/api
    restart: always
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: "npm run dev"
    environment:
      - AXIOS_BASEURL=https://funny-how.com/api
      - AXIOS_BROWSER_BASEURL=/api

volumes:
  postgres-data:
  static-data:
