services:
  nginx:
    container_name: nginx
    build:
      context: ./proxy/
      dockerfile: Dockerfile
    ports:
      - '443:443'
    volumes:
      - './backend:/app/'
      - './proxy/nginx-prod.conf:/etc/nginx/nginx.conf'
      - './proxy/certbot/www/:/var/www/certbot/'
      - './proxy/certbot/conf/:/etc/nginx/ssl'
    depends_on:
      - backend
      - frontend
    networks:
      - funny

  backend:
    build:
      context: ./backend/php/
      dockerfile: Dockerfile-production
      args:
        WWWUSER: 'laravel'
        WWWUID: '1000'
    container_name: php
    volumes:
      - './backend:/app/'
    depends_on:
      - db
    networks:
      - funny

    env_file:
      - .env
    environment:
      - AXIOS_BASEURL_CLIENT=https://funny-how.com

#  certbot:
#    container_name: certbot
#    image: certbot/certbot:latest
#    volumes:
#      - ./proxy/certbot/www/:/var/www/certbot/:rw
#      - ./proxy/certbot/conf/:/etc/letsencrypt/:rw
#    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
#    networks:
#      - funny

  frontend:
    container_name: frontend
    build:
      context: ./frontend/client
      dockerfile: Dockerfile-prod
      args:
        - NODE_ENV=production
        - AXIOS_BASEURL=http://nginx
        - AXIOS_BASEURL_CLIENT=https://funny-how.com
        - AXIOS_API_VERSION=/api/v1
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - AXIOS_BASEURL=http://nginx
      - AXIOS_BASEURL_CLIENT=https://funny-how.com
      - AXIOS_API_VERSION=/api/v1
      - GOOGLE_MAPS_API=${GOOGLE_MAPS_API:-default_map_key}
    networks:
      - funny

volumes:
  postgres-data:
  static-data:
