version: "3.9"
services:
  backend:
    container_name: backend
    build:
      context: ./backend/php/
      dockerfile: Dockerfile
    restart: always
    expose:
      - "9000"
    ports:
      - "9000:9000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - funny

  frontend:
    container_name: frontend
    build:
      context: ./frontend/client
      dockerfile: Dockerfile
      args:
        - AXIOS_BASEURL=https://funny-how.com/api
        - AXIOS_BROWSER_BASEURL=/api
    restart: always
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: "npm run dev"
    environment:
      - AXIOS_BASEURL=https://funny-how.com/api
      - AXIOS_BROWSER_BASEURL=/api

volumes:
  postgres-data:
  static-data:
