version: "3.9"
services:
  nginx:
    container_name: nginx
    build:
      context: ./proxy/
      dockerfile: Dockerfile
    ports:
      - '443:443'
    volumes:
      - './backend:/app/'
      - './proxy/nginx-prod.conf:/etc/nginx/nginx.conf'
#      - '/etc/letsencrypt/ssl/fullchain.pem:/etc/nginx/ssl/fullchain.pem'
#      - '/etc/letsencrypt/ssl/privkey.pem:/etc/nginx/ssl/privkey.pem'
    depends_on:
      - backend
      - frontend
    networks:
      - funny

  backend:
    build:
      context: ./backend/php/
      args:
        WWWUSER: 'laravel'
        WWWUID: '1000'
    container_name: php
    volumes:
      - './backend:/app/'
    depends_on:
      - db
    networks:
      - funny
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  frontend:
    container_name: frontend
    build:
      context: ./frontend/client
      dockerfile: Dockerfile
      args:
        - AXIOS_BASEURL=https://funny-how.com/api
        - AXIOS_BROWSER_BASEURL=/api
    restart: always
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: "npm run dev"
    environment:
      - AXIOS_BASEURL=https://funny-how.com/api
      - AXIOS_BROWSER_BASEURL=/api
    networks:
      - funny

volumes:
  postgres-data:
  static-data:
