export { default as IconPrice } from './IconPrice.vue'
export { default as IconRating } from './IconRating.vue'
export { default as IconSearch } from './IconSearch.vue'
export { default as IconStatus } from './IconStatus.vue'
export { default as IconButton } from './IconButton.vue'
