ENV HOST=0.0.0.0
RUN apk update
ARG NODE_VERSION=20.11.0
ARG AXIOS_BASEURL
ARG AXIOS_BROWSER_BASEURL

FROM node:${NODE_VERSION}-alpine

# Set the working directory
WORKDIR /usr/src/app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm ci

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

# Expose the necessary port and start the server
EXPOSE 3000
CMD ["node", "/usr/src/app/.output/server/index.mjs"]