FROM php:8.1-fpm

# Arguments defined in docker-compose.yml
ARG WWWUSER
ARG WWWUID

# Set working directory
WORKDIR /app/

ENV DEBIAN_FRONTEND noninteractive
ENV TZ=UTC

# Install system dependencies
RUN apt-get update && apt-get install -y \
    libpq-dev \
    libicu-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libxml2-dev \
    libgmp-dev \
    libzip-dev \
    zip \
    unzip \
    curl \
    git \
    libmagickwand-dev --no-install-recommends \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-install -j$(nproc) iconv mysqli pdo_pgsql pdo_mysql soap bcmath gmp intl opcache zip sockets

# Install Imagick
RUN pecl install imagick \
    && docker-php-ext-enable imagick

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Create system user to run Composer and Artisan Commands
RUN useradd -G www-data,root -u $WWWUID -d /home/$WWWUSER $WWWUSER \
    && mkdir -p /home/$WWWUSER/.composer \
    && chown -R $WWWUSER:$WWWUSER /home/$WWWUSER

COPY php-production.ini /etc/php/8.1/fpm/conf.d/xy-custom.ini

# Install Supercronic
ARG SUPERCRONIC_URL=https://github.com/aptible/supercronic/releases/download/v0.2.29
ARG SUPERCRONIC=supercronic-linux-amd64
ARG SUPERCRONIC_SHA1SUM=cd48d45c4b10f3f0bfdd3a57d054cd05ac96812b
RUN curl -fsSLO "$SUPERCRONIC_URL/$SUPERCRONIC" \
    && echo "$SUPERCRONIC_SHA1SUM $SUPERCRONIC" | sha1sum -c - \
    && chmod +x "$SUPERCRONIC" \
    && mv "$SUPERCRONIC" "/usr/local/bin/supercronic"

# Ensure cron directory exists and set up cron
COPY cron-schedule.sh /usr/local/bin/cron-schedule.sh
RUN chmod +x /usr/local/bin/cron-schedule.sh

# Copy the rest of the application code
COPY --chown=$WWWUSER:$WWWUSER . .

# Ensure storage, logs, and cron directory has the correct permissions
RUN mkdir -p /app/storage /app/logs /app/cron.d \
    && chown -R $WWWUSER:www-data /app/storage /app/logs /app/cron.d \
    && chmod -R 775 /app/storage /app/logs /app/cron.d

USER $WWWUSER

CMD ["php-fpm"]