export { default as IconCheck } from "./IconCheck.vue"
export { default as IconCopyright } from "./IconCopyright.vue"
export { default as IconElipse } from "./IconElipse.vue"
export { default as IconLeft } from "./IconLeft.vue"
export { default as IconRight } from "./IconRight.vue"
export { default as IconLine } from "./IconLine.vue"
export { default as IconMic } from "./IconMic.vue"
export { default as IconUser } from "./IconUser.vue"
export { default as IconDown } from "./IconDown.vue"
export { default as IconTrash } from "./IconTrash.vue"
export { default as IconUpload } from "./IconUpload.vue"
export { default as IconHeadphones } from "./IconHeadphones.vue"
export { default as IconMonitor } from "./IconMonitor.vue"
export { default as IconClock } from "./IconClock.vue"
export { default as IconCalendar } from "./IconCalendar.vue"
export { default as IconAddRing } from "./IconAddRing.vue"
export { default as IconClose } from "./IconClose.vue"
export { default as IconPeople } from "./IconPeople.vue"
export { default as IconWeed } from "./IconWeed.vue"
export { default as IconBurger } from "./IconBurger.vue"

export { default as IconBooking } from "./IconBooking.vue"
export { default as IconClients } from "./IconClients.vue"
export { default as IconHistory } from "./IconHistory.vue"

export { default as IconLike } from "./IconLike.vue"
export { default as IconPricetag } from "./IconPricetag.vue"
export { default as IconNav } from "./IconNav.vue"
export { default as IconCopy } from "./IconCopy.vue"
export { default as IconCheckmark } from "./IconCheckmark.vue"

export { default as IconPhone } from "./IconPhone.vue"
export { default as IconEmail } from "./IconEmail.vue"
export { default as IconStat } from "./IconStat.vue"

export { default as IconApplePay } from "./IconApplePay.vue"
export { default as IconGooglePay } from "./IconGooglePay.vue"
export { default as IconMastercard } from "./IconMastercard.vue"
export { default as IconVisa } from "./IconVisa.vue"

export { default as IconBackDraw } from "./IconBackDraw.vue"

export { default as IconNumbers } from "./IconNumbers.vue"

export { default as IconCredit } from "./IconCredit.vue"
export { default as IconDollar } from "./IconDollar.vue"

export { default as IconStripe } from "./IconStripe.vue"
export { default as IconSquare } from "./IconSquare.vue"

export { default as IconTeam } from "./IconTeam.vue"
export { default as IconPhotoPlaceholder } from "./IconPhotoPlaceholder.vue"
