# Базовый образ Node.js
FROM node:20.11-alpine3.19

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем только production-зависимости
RUN npm install --production

# Открываем порт для WebSocket сервера
EXPOSE 6001

# Копируем все файлы проекта
COPY . .

# Запускаем сервер
CMD ["npm", "start"]
