name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

#      - name: Build Docker images
#        env:
#          DB_HOST: ${{ secrets.DB_HOST }}
#          DB_DATABASE: ${{ secrets.DB_DATABASE }}
#          DB_USERNAME: ${{ secrets.DB_USERNAME }}
#          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
#        run: make build-prod
#
#      - name: Run tests
#        env:
#          DB_HOST: ${{ secrets.DB_HOST }}
#          DB_DATABASE: ${{ secrets.DB_DATABASE }}
#          DB_USERNAME: ${{ secrets.DB_USERNAME }}
#          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
#        run: |
#          make composer
#          make migrate

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Add SSH key to known hosts
        run: ssh-keyscan -H ${{ secrets.HOST_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        env:
          HOST_USER: ${{ secrets.HOST_USER }}
          HOST_IP: ${{ secrets.HOST_IP }}
          HOST_PASSWORD: ${{ secrets.HOST_PASSWORD }}
        run: |
          ssh $HOST_USER@$HOST_IP "
            cd /home/ubuntu/funny-how &&
            make stop &&
            make clean &&
            make build-prod &&
            make composer-prod &&
            make migrate-prod &&
            make start-prod &&
            make optimize-prod &&
            docker system prune -af"
