name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

  #      - name: Build Docker images
  #        run: make build-prod
  #
  #      - name: Run tests
  #        run: |
  #          make composer
  #          make migrate

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}

      - name: Create .ssh directory
        run: mkdir -p ~/.ssh

      - name: Add SSH key to known hosts
        run: ssh-keyscan -H ${{ secrets.HOST_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        env:
          HOST_USER: ${{ secrets.HOST_USER }}
          HOST_IP: ${{ secrets.HOST_IP }}
        run: |
          ssh $HOST_USER@$HOST_IP 'bash -c "
            cd /home/ubuntu/funny-how &&
            make stop &&
            make clean &&
            make build-prod &&
            make composer-prod &&
            make migrate-prod &&
            make start-prod &&
            make optimize-prod &&
            docker system prune -af"'
