name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}

      - name: Create .ssh directory
        run: mkdir -p ~/.ssh

      - name: Add SSH key to known hosts
        run: ssh-keyscan -H ${{ secrets.AWS_INSTANCE_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to AWS EC2
        env:
          AWS_INSTANCE_IP: ${{ secrets.AWS_INSTANCE_IP }}
          AWS_USER: ${{ secrets.AWS_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no $AWS_USER@$AWS_INSTANCE_IP 'bash -c "
            cd /home/ubuntu/funny-how &&
            make update-prod-container
